name: 'netlify cd'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ PXE7_LofxBQCwD0O7jNokHvlTj1Ir24xf4qjymYizPw }}
          NETLIFY_DEPLOY_TO_PROD: true
